services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - net_con

  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 8s
      timeout: 10s
      retries: 15
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    mem_limit: 3g
    ports:
      - '9200:9200'
    networks:
      net_con:

  kibana01:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      es01:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 8s
      timeout: 10s
      retries: 15
    volumes:
      - kibana01:/usr/share/kibana/data
    ports:
      - '5601:5601'
    networks:
      net_con:

  pg_db:
    container_name: pg_db
    image: postgres:16
    environment:
      - POSTGRES_USER=${PG_ADMIN}
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ADMIN}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./secrets/dumps:/docker-entrypoint-initdb.d
    networks:
      net_con:

  web_app:
    build: .
    environment:
      - ENV_FILE=/run/secrets/.env
    depends_on:
      pg_db:
        condition: service_healthy
      es01:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    secrets:
      - .env
    ports:
      - '8100:8000'
    networks:
      net_con:


volumes:
  kibana01:
    driver: local
  esdata01:
    driver: local
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  net_con:
    driver: bridge
    name: katk_net

secrets:
  .env:
    file: .env
