apiVersion: 1

# Политики маршрутизации уведомлений
policies:
  - orgId: 1
    receiver: Telegram Alerts
    group_by:
      - '...'  # Группировать по всем labels (каждый уникальный алерт отдельно)
    group_wait: 5s
    group_interval: 10s
    repeat_interval: 5m
    routes:
      - receiver: Telegram Alerts
        matchers:
          - severity = critical
        group_wait: 5s
        group_interval: 10s
        repeat_interval: 5m
      - receiver: Telegram Alerts
        matchers:
          - severity = warning
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 15m
